const RX_ONE_ENDPOINTS = {
  USER: {
    SIGN_UP: "signup/user",
    LOGIN: "login/user",
    FORGOT_PASSWORD: "user/forgot/password",
    CHANGE_PASSWORD: "user/change/password",
    RESEND_CONFIRMATION_EMAIL: "user/resend/confirmation",
    KEYS: "user/keys",
    REFERRAL_LINK: "user/referral/link",
    SEND_REFERRAL_EMAILS: "mail/referral/link",
    KYC_STATUS: "user/kyc/status",
    KYC_FORM_CONTACT_INFO: "user/kyc/contact/details",
    KYC_FORM_BUSINESS_DETAILS: "user/kyc/business/details",
    KYC_FORM_ACCOUNT_DETAILS: "user/kyc/account/details",
    KYC_DOCS_VERIFICATION_BUSINESS_PAN: "user/kyc/documents/business/pan",
    KYC_DOCS_VERIFICATION_INCORP_CERTI: "user/kyc/documents/incorp/cert",
    KYC_DOCS_VERIFICATION_SIGNATORY_ID: "user/kyc/documents/auth/signatory",
    KYC_SUBMIT: "user/kyc/documents/submit",
  },
  REWARDS: {
    REDEEM: {
      GET_REWARDS_LIST: "rxone/user/list/rewards",
      GET_POINTS_BALANCE: "rxone/user/points/balance",
      GET_REWARD_IMAGE: "rxone/user/get/reward/image",
      GET_REWARD_DETAILS: "rxone/user/get/reward/details",
      POST_AVAIL_REWARD: "rxone/user/redeem/reward/points",
    },
    POINTS_HISTORY: {
      GET_POINTS_HISTORY: "rxone/user/points/history",
    },
  },
  SETTLEMENTS: {
    LIST_SETTLEMENTS: "rxone/user/payment/settlement/status",
  },
  SUBSCRIPTIONS: {
    GET_A_QUOTE: "rxone/premium/quote/request",
  },
  NOTIFICATION: {
    GET_NOTIFICATION: "rxone/user/fetch/notifications",
    DELETE_NOTIFICATION: "rxone/user/close/notification",
  },
  SETTINGS: {
    LIST_FACILITY_STAFF: "list/facility/users",
    SWITCH_STAFF_ACCESS: "facility/user/access/switch",
    REGISTER_USER: "register/facility/user",
    USER_DETAILS: "facility/user/operations",
  },
  
};

const RX_OPD_ENDPOINTS = {
  HOSPITAL: {
    GET_HOSPITAL_REPORT_COLLECTION: "hospital/reporting/collection",
    GET_HOSPITAL_REPORT_APPOINTMENTS: "hospital/reporting/appointments/count",
    FETCH_A_HOSPITAL: "hospital/registration/record",
    ALL_HOSPITALS: "hospital",
    LIST_HOSPITAL_CALENDAR: "hospital/holiday",
    CREATE_PATIENT_PORTAL_QR: "hospital/portal/qr/patient",
    GET_PATIENT_PORTAL_QR: "hospital/patient/portal/qr",
    GET_DOCTOR_PORTAL_QR: "hospital/doctor/portal/qr",
    CREATE_DOCTOR_PORTAL_QR: "hospital/portal/qr/doctor",
    CHECK_FACILITY_SHORT_NAME: "hospital/check/shortname",
    REGISTER_HOSPITAL: "hospital",
    UPLOAD_HOSPITAL_DOCS: "hospital/reg/documents",
    GET_HOSPITAL_LOGO: "hospital/logo",
    CHANGE_HOSPITAL_LOGO: "hospital/change/logo",
    GET_HOSPITAL: "hospital/profile/record",
    UPDATE_HOSPITAL: "hospital/profile/record",
    DELETE_HOSPITAL: "hospital/delete/record",
    APPOINTMENTS: "hospital/appointments",
    RMP_SEARCH: "hospital/find/nmc/rmp",
    FETCH_A_DOCTOR: "hospital/doctor/registration/details",
    GET_DOCTOR_AVATAR: "doctor/avatar",
    ALL_DOCTORS: "hospital/doctors",
    REGISTER_DOCTOR: "hospital/doctors",
    // REGISTER_DOCTOR: "hospital/portal/qr/doctor",
    CREATE_DOCTOR_RECURRING_SCHEDULE: "hospital/doctor/recurring/schedule",
    FETCH_DOCTOR_RECURRING_SCHEDULE: "hospital/doctor/fetch/recurring/schedule",
    CREATE_DOCTOR_DAY_SCHEDULE: "hospital/doctor/schedule/ops",
    FETCH_DOCTOR_DAY_SCHEDULE: "hospital/doctor/schedule/ops",
    UPLOAD_DOCTOR_DOCS: "hospital/doctor/upload/documents",
    SWITCH_DOCTOR_AVAILABILITY: "hospital/doctor/available/switch",
    UPDATE_DOCTOR_CONSULT_CHARGES: "hospital/doctor/charges/update",
    UPDATE_DOCTOR_ONLINE_DISCOUNT: "hospital/doctor/online/discount/update",
    UPDATE_DOCTOR_SCHEDULE: "/hospital/doctor/schedule/ops",
    DELETE_DOCTOR: "hospital/doctor/remove/profile",
    OPD: {
      LIST_PATIENTS: "facility/list/patients",
      CREATE_PATIENT_PROFILE: "facility/create/patient/profile",
      ADD_TO_EXSISTING_PROFILE: "facility/patient/family/profile",
      LIST_AVAILABLE_DOCTORS: "facility/list/doctors",
      LIST_AVAILABLE_SLOTS: "facility/doctor/slots",
      INITIATE_APPOINTMENT_BOOKING: "facility/initiate/appointment",
      INITIATE_APPOINTMENT_ORDER: "facility/initiate/order",
      VERIFY_ONLINE_PAYMENT: "facility/verify/payment",
      CONFIRM_BOOK_APPOINTMENT_CASH_PAYMENT: "facility/confirm/cash/payment",
      LIST_UNPAID_CASH_ORDERS: "hospital/list/unpaid/orders",
      CONFIRM_CASH_PAYMENT: "order/cash/payment",
      LIST_INVOICES: "hospital/appointment/invoices",
      GENERATE_INVOICE: "hospital/generate/opd/invoices",
    },
    APPOINTMENT: {
      LIST_ALL_DOCTORS: "hospital/list/all/doctors",
      LIST_DOCS_APPOINTMENTS: "hospital/doc/list/appointments",
      FETCH_APPOINTMENT_DETAILS: "hospital/appointment/details",
      FETCH_APPOINTMENT_LINEAGE: "hospital/appointment/lineage",
      PATIENT_PROFILE: "hospital/patient/profile/pic",
      CANCEL_APPOINTMENT: "appointment/cancel",
    },
  },
  PHARMACY: {
    PHARMACY_LIST: "pharma/master"
  },
};

export { RX_ONE_ENDPOINTS, RX_OPD_ENDPOINTS };
